task_a:
  general:
    dataset_dir: Datasets/celeba/img/
    label_csv_path: Datasets/celeba/labels.csv
    x_header_name: img_name
  a1:
    y_header_name: gender
    cropped_dataset_dir: Datasets/processed/celeba_cropped_face/
    model_path: models/result/a1.pkl
    log_path: A1/log.txt
    lbp:
      n_points: 8
      radius: 1
      method: default
    svm:
      param_candidates:  
        C: [1, 10, 100]    
  a2:
    y_header_name: smiling
    cropped_dataset_dir: Datasets/processed/celeba_cropped_mouth/
    model_path: models/result/a2.pkl
    log_path: A2/log.txt
    lbp:
      n_points: 8
      radius: 1
      method: default
    svm:
      param_candidates:
        C: [1, 10, 100]

task_b:
  general:
    dataset_dir: Datasets/cartoon_set/img/
    label_csv_path: Datasets/cartoon_set/labels.csv
    x_header_name: file_name
  b1:
    y_header_name: face_shape
    cropped_dataset_dir: Datasets/processed/cartoon_set_cropped_face_shape/
    log_path: B1/log.txt
    model_path: models/result/b1.pkl
    svm:
      param_candidates:
        C: [1, 10, 100]
  b2:
    y_header_name: eye_color
    cropped_dataset_dir: Datasets/processed/cartoon_set_cropped_eye/
    log_path: B2/log.txt
    model_path: models/result/b2.pkl
    haar_cascade_path: models/helper/haarcascades/haarcascade_eye.xml
    svm:
      param_candidates:
        C: [1, 10, 100]

shape_predictor:
  model_dir: models/helper/shape_predictor_68_face_landmarks.dat
  mouth:
    start: 48
    end: 68
  right_eye:
    start: 36
    end: 42
  jaw:
    start: 0
    end: 17

train:
  test_proportion: 0.2
  random_state: 18154195
  max_iter: 10000000
  tol: 0.00001
  k_crossval: 5